add appsync visibility option
terraform-aws-modules/terraform-aws-appsync pull request #50
Opened 2023-06-03 21:47 UTC by itaywol

## Description

AWS added a feature to AppSync to allow creating private APIs ([link to the article](https://docs.aws.amazon.com/appsync/latest/devguide/using-private-apis.html)).
Corresponding to that a [PR](https://github.com/hashicorp/terraform-provider-aws/pull/31369) aws merged into release [5.1.0](https://github.com/hashicorp/terraform-provider-aws/releases/tag/v5.1.0) of terraform-provider-aws.

In my PR i have added the visibility option to the appsync module.

## Motivation and Context

It adds a missing feature.

## Breaking Changes

None.

## How Has This Been Tested?
- [x] I have updated at least one of the `examples/*` to demonstrate and validate my change(s)
- [x] I have tested and validated these changes using one or more of the provided `examples/*` projects

- [x] I have executed `pre-commit run -a` on my pull request

2023-06-04 07:56 UTC, itaywol commented
@antonbabenko Kindly review this please 🙏🏻

2023-06-05 17:32 UTC, antonbabenko requested changes

2023-06-05 17:32 UTC, antonbabenko commented on variables.tf
> +  default     = "GLOBAL"
```suggestion
  default     = null
```

2023-06-05 17:32 UTC, antonbabenko commented on variables.tf
> +  validation {
Please remove this `validation` block completely.

2023-06-05 21:13 UTC, antonbabenko approved these changes

2023-06-05 21:13 UTC, merged

2023-06-05 21:14 UTC, antonbabenko commented
This PR is included in version 2.0.0 :tada: