feat: add appsync arguments to support appsync security features
terraform-aws-modules/terraform-aws-appsync pull request #61
Opened 2024-03-11 16:25 UTC by jagoodhand

## Description
Add support for the new AppSync GraphQL controls for query depth, run complexity and introspection.

## Motivation and Context
This enables users to utilise the new AppSync features that improve the security of their AppSync APIs.

## Breaking Changes
This increases the minimum AWS provider version to 5.37, as this was the terraform provider that implemented these controls.

## How Has This Been Tested?
- [x] I have updated at least one of the `examples/*` to demonstrate and validate my change(s)
- [x] I have tested and validated these changes using one or more of the provided `examples/*` projects
- [x] I have executed `pre-commit run -a` on my pull request

2024-03-13 12:37 UTC, jagoodhand commented
@antonbabenko could I request your review on this PR please?

2024-03-20 12:06 UTC, jagoodhand commented
@antonbabenko - is there anything else you would need me to do on this PR before it can be merged? Thanks.

2024-03-20 12:38 UTC, antonbabenko requested changes

2024-03-20 12:38 UTC, antonbabenko commented on variables.tf
> +  default     = "ENABLED"
Please change the default value for all 3 new variables to `null` and remove `validation` section entirely from all variables.

2024-03-20 13:10 UTC, jagoodhand commented
@antonbabenko - done. Would you mind re-reviewing please?

2024-03-20 13:11 UTC, antonbabenko approved these changes

2024-03-20 13:11 UTC, merged

2024-03-20 13:12 UTC, antonbabenko commented
This PR is included in version 2.5.0 :tada: